apiVersion: apps/v1
kind: Deployment
metadata:
  name: ct-client
  namespace: climatetrackr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ct-client
  template:
    metadata:
      labels:
        app: ct-client
    spec:
      containers:
        - name: climatetrackr-client
          image: mrapanu/climatetrackr-client:latest
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: ct-secrets
                  key: API_URL
