apiVersion: v1
kind: Service
metadata:
  name: ct-client-lb
  namespace: climatetrackr
spec:
  selector:
    app: ct-client
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 80
  type: LoadBalancer
