apiVersion: v1
kind: PersistentVolume
metadata:
  name: ct-pv
  namespace: climatetrackr
spec:
  capacity:
    storage: 5Gi # Adjust size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /path/to/nfs/volume # Replace with actual NFS path
    server: nfs-server-address # Replace with NFS server address
