apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-volume
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: <YOUR_NFS_ADDRESS>
    path: "/shared/kubernetes/monitoring"