apiVersion: v1
kind: "PersistentVolumeClaim"
metadata:
  name: prometheus-volume
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi