apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer
  namespace: portainer
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: <YOUR_NFS_SERVER>
    path: "/shared/kubernetes/portainer"
