apiVersion: v1
kind: "PersistentVolumeClaim"
metadata:
  name: portainer
  namespace: portainer
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi