apiVersion: v1
kind: "PersistentVolumeClaim"
metadata:
  name: dashy-config-volume
  namespace: dashy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 250Mi