apiVersion: v1
kind: PersistentVolume
metadata:
  name: dashy-config-volume
  namespace: dashy
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: <NFS_SERVER_IP>
    path: "/shared/kubernetes/dashy"