apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: dashy
spec:
  type: LoadBalancer
  selector:
    app: dashy
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
      name: http